# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2f547129a97ee32912349b01fe25a7e77074199f76fb1b6e0ac4d3b2fb53ae224b28dd74b7071389dd9ab224b655bd05ae2311d5011f80bb68e68c71c43c576

test:
  secret_key_base: e0fb2c16ab9f93722d45d24eb9c22799d941fb6d1ea48bcdbf06c4131f48bcf5d8fca633efb0a51fbaa9badbd783a2ed2ff025895d3da2b5869fdcc7b1a68f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
